### ISSUE TITLE
Java 1.6 support

### ISSUE THREAD

**Issue by pearj** [mattsheppard/gethostname4j#1]
First issue!

Hi Matt,

Thanks for creating this. Are you able to add Java 1.6 support at least?

I think [JNA](https://github.com/java-native-access/jna) actually supports Java 1.4 and onwards according to the README.

**Comment by mattsheppard** [comment]
Ought to to be fixed in 0.0.2, which I've just pushed to maven central - In my experience, it takes a while (maybe a few hours) before it is visible everywhere.

Please let me know if you have any trouble with it!
