### ISSUE TITLE
LICENSE file on Maven Central jar

### ISSUE THREAD

**Issue by beluchin** [mattsheppard/gethostname4j#6]
Hello, could you add the LICENSE file to the jar in Maven Central? Otherwise I cannot use it within my corporation. Thanks

**Comment by mattsheppard** [comment]
Sure - FYI it is declared in the pom.xml under META-INF/maven/com.kstruct/gethostname4j/pom.xml if that helps at all.

Assuming not, I'll try to get to it soon.

If you have chance to give me an pull request for it, that would be helpful :)

**Comment by mattsheppard** [comment]
Poked about briefly - Where exactly are you expecting the file to reside within the .jar?

Would inside `META-INF/LICENSE.txt` suit, or is there some standard I'm unaware of? I looked at a few other .jar files for common libraries in maven central and commons-io was the first one I could see that had such a file, and they put it under `META-INF/LICENSE.txt`.

**Comment by mattsheppard** [comment]
Started working on it under https://github.com/mattsheppard/gethostname4j/pull/7 - Seems to work.

I'll hold on to it until you confirm your desired path for the file though @beluchin.

**Comment by beluchin** [comment]
Hey, many thanks for your prompt reply. I asked "where does the script look
for the license" to the FRS people at work and they say:


*should be normal way ... but if they can put the name of the licenses and
not the url that would be nice.http://maven.apache.org/pom.html#Licenses
<http://maven.apache.org/pom.html#Licenses>*

Does that help?

Thanks again

**Comment by beluchin** [comment]
hold on - I just realized there is no pom on clojure projects. Give me a
few minutes to inquire further.

**Comment by beluchin** [comment]
it worked now. I don't know what I did wrong. Apologies for the confusion.
I will close the issue on Github.

Thanks again.

**Comment by mattsheppard** [comment]
No worries - Glad it's working for you now!
